Add, Delete, View Consultation & Changed Delete to Index System
AY2122S2-CS2103T-T11-1/tp pull request #58
Opened 2022-03-16 19:45 UTC by juslam19

### Changes and Issues

_**Edit: Just Added 19/3/2022**_

_Changed Delete Consultation to Index system._ 

**What's in this PR?**

Add, View and Delete Consultation commands implemented. JavaDocs has been properly added for all the statements, and all stray print statements have been nuked.

Tests for consultation have yet to be added, however from basic testing seems to function properly, and checked that does not allow duplicate consultations.

Lastly, I have read all your previous comments and implemented them as such. Thank you, and hope this version is appropriate for merging.

**Persisting Issues**

However, there is still the inconsistent switching between person and patient in method names e.g. getPersonList. I suggest we should find some find and replace function (that is case sensitive, otherwise methods' camelCase would be butchered up) or something to change all these for consistency.

Moreover, some of the messages for commands incorrectly mention "list" instead of "view". Changed for Consultation, I suggest everybody else changes theirs as well.

2022-03-17 07:01 UTC, joey-chance requested changes
Some minor fixes to JavaDocs, naming convention and line breaks. After fixing these, it LGTM! 👍

2022-03-17 07:01 UTC, joey-chance commented on src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
> +//}
Why is this file commented out?

2022-03-17 07:07 UTC, clement0010 requested changes

2022-03-17 07:13 UTC, clement0010 commented
Hello,

Here are my comments for this PR:
1. It is too big. 3 issues lumped into one PR makes it difficult to test and review. It would be better to split them into separate PR and adopt the breadth-first iteration style.
2. PR title does not match the change in the codebase. I thought this PR was a codestyle fix rather than extending functionalities. Consider updating it?
3. PR description is missing. Ideally, it should contain a brief outline of the change for brevity. For example, I find it difficult to understand why was the test cases disabled and it was not elaborated in the description. Consider adding a description?
5. When the code is ready perhaps change the PR as `Ready for review`?

2022-03-17 07:16 UTC, juslam19 commented on src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
> -    private static final String VALID_NRIC = BENSON.getNric().toString();
It was to comply with the Checkstyle test, which insisted that constants must be final and static or something to qualify for capital letters. Otherwise the thing won't let me pass.

2022-03-17 07:32 UTC, cheekean5848 commented on src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
> -}
Maybe you shouldn't disable the test case for this? And also this has no effect on your implementation right?

2022-03-17 07:34 UTC, juslam19 commented on src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
> -}
It refuses to work for some reason, and since it was not my part, I just disabled it thinking that others were having issues too.

2022-03-17 07:34 UTC, juslam19 commented on src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
> -}
I will take a closer look at why it might not be working.

2022-03-17 07:41 UTC, cheekean5848 commented on src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
> -}
have you included your json property in the test file?

2022-03-17 09:49 UTC, juslam19 commented
Add, View and Delete Consultation commands implemented. JavaDocs has been properly added for all the statements, and all stray print statements have been nuked. 

Tests for consultation have yet to be added, however from basic testing seems to function properly, and checked that does not allow duplicate consultations. 

However, there is still the inconsistent switching between person and patient in method names e.g. getPersonList. I suggest we should find some find and replace function (that is case sensitive, otherwise methods' camelCase would be butchered up) or something to change all these for consistency.

Moreover, some of the messages for commands incorrectly mention "list" instead of "view". Changed for Consultation, I suggest everybody else changes theirs as well.

2022-03-17 13:36 UTC, joey-chance commented on src/main/java/seedu/address/model/consultation/Date.java
> +    private static final String VALIDATION_REGEX = "^(3[01]|[12][0-9]|0[1-9])-(1[0-2]|0[1-9])-[0-9]{4}$";
If you use LocalDate to check the input, you don't need a validation regex anymore.

2022-03-18 16:23 UTC, cheekean5848 reviewed
Just remove all the debugging print, other than this, all looks good to me

2022-03-18 16:23 UTC, cheekean5848 commented on src/main/java/seedu/address/logic/commands/CommandType.java
> +        System.out.println(viewCommandType);
Maybe should delete this?

2022-03-18 16:36 UTC, joey-chance requested changes

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/logic/commands/CommandType.java
> +        System.out.println(viewCommandType);
Remove unnecessary print statements.

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/model/Model.java
> +
Extra line

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/model/Model.java
> +
Extra line

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/model/consultation/Consultation.java
> +        //.append(getTestAndResults());
Ideally this should be omitted

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/model/consultation/Date.java
> +public class Date {
I think you can consider changing this to ConsultationDate to avoid any confusion with Java's own Date class and our other Date classes too.

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/model/consultation/Notes.java
> +
Extra line

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/model/consultation/Time.java
> +public class Time {
You can also consider changing this to ConsultationTime for clarity.

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
> +    private final String ownerNric;
Can consider changing this to patientNric to make it standardized with the others.

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/ui/MainWindow.java
> +
Extra line

2022-03-18 16:36 UTC, joey-chance commented on src/main/java/seedu/address/ui/MainWindow.java
> +            personListPanelPlaceholder.getChildren().clear();
Can you explain why some are .clear() and some are .remove(0)? What's the difference?

2022-03-18 16:36 UTC, joey-chance commented on src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
> +        System.out.println(TYPICAL_PERSONS_FILE);
Remove this.

2022-03-18 16:40 UTC, juslam19 commented on src/main/java/seedu/address/model/consultation/Consultation.java
> +        //.append(getTestAndResults());
This will be added back in the later versions.

2022-03-18 16:41 UTC, juslam19 commented on src/main/java/seedu/address/ui/MainWindow.java
> +            personListPanelPlaceholder.getChildren().clear();
Clear removes all the elements inside the box. It is better as sometimes remove(0) does not work properly.

2022-03-18 16:48 UTC, joey-chance commented on src/main/java/seedu/address/ui/MainWindow.java
> +            personListPanelPlaceholder.getChildren().clear();
Can you elaborate on when it does not work properly?

2022-03-18 16:50 UTC, joey-chance approved these changes
LGTM! 👍

2022-03-18 17:00 UTC, clement0010 approved these changes
LGTM! Great job

2022-03-19 07:11 UTC, merged